-- auto Generated on 2020-04-07
-- DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`(
	`UID` VARCHAR (32) NOT NULL COMMENT 'uid',
	USER_NAME VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'userName',
	AGE VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'age',
	PHONE VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'phone',
	ADDRESS VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'address',
	EMAIL VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'email',
	PRIMARY KEY (`UID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'user';
